application: haitaiblog
version: 1
runtime: python27
api_version: 1
threadsafe: no

skip_files: |
 ^(.*/)?(
 (.*/\.svn/.*)|
 (.*\.py[co])|
 (.*/Thumbs\.db)|
 )$

default_expiration: "3650d"

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

- url: /rpc|/rpc|rsd.xml
  script: api_rpc.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

- url: /_ah/mail/.+
  script: main.py 
  login: admin

- url: /admin/.*|/admin
  script: $PYTHON_LIB/google/appengine/ext/admin 
  login: admin

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: django
  version: "1.2"